[package]
name = "vimwiki2org"
version = "0.1.0"
authors = ["Pengcheng Ding <info@desmonding.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
glob = "0.3.0"
pandoc = "0.8.2"
